"""Policy/value-guided MCTS for Game of Y.

This agent follows the AlphaZero-style shape, but keeps the implementation
small and dependency-free:

* a NumPy MLP predicts a policy over board cells and a value for the side to move
* training data is generated by a stronger plain-MCTS teacher
* search uses PUCT selection with network priors and blended value/rollout leaves
"""

import math
import os
import pickle
import random
from dataclasses import dataclass

import numpy as np


N_CELL_FEATURES = 6  # empty, mine, opponent, left side, right side, bottom side


def _cell_index(row, col):
    return row * (row + 1) // 2 + col


def _index_to_cell(index):
    row = 0
    while index >= row + 1:
        index -= row + 1
        row += 1
    return row, index


def _num_cells(board_size):
    return board_size * (board_size + 1) // 2


def _board_features(game):
    """Encode board from ``game.current_player``'s perspective."""
    board = game.board
    size = board.size
    me = game.current_player
    opp = 3 - me
    feats = np.zeros(_num_cells(size) * N_CELL_FEATURES + 2, dtype=np.float64)

    for r in range(size):
        for c in range(r + 1):
            idx = _cell_index(r, c) * N_CELL_FEATURES
            v = board.get_cell(r, c)
            feats[idx] = 1.0 if v == 0 else 0.0
            feats[idx + 1] = 1.0 if v == me else 0.0
            feats[idx + 2] = 1.0 if v == opp else 0.0
            feats[idx + 3] = 1.0 if c == 0 else 0.0
            feats[idx + 4] = 1.0 if c == r else 0.0
            feats[idx + 5] = 1.0 if r == size - 1 else 0.0

    n_cells = _num_cells(size)
    feats[-2] = len(game.move_history) / max(1, n_cells)
    feats[-1] = 1.0
    return feats


def _softmax_masked(logits, legal_indices, temperature=1.0):
    probs = np.zeros_like(logits, dtype=np.float64)
    if not legal_indices:
        return probs

    legal_logits = logits[np.array(legal_indices, dtype=np.int64)] / max(temperature, 1e-6)
    legal_logits = legal_logits - np.max(legal_logits)
    exp_logits = np.exp(np.clip(legal_logits, -60.0, 60.0))
    denom = float(np.sum(exp_logits))
    if denom <= 0.0 or not np.isfinite(denom):
        probs[legal_indices] = 1.0 / len(legal_indices)
    else:
        probs[legal_indices] = exp_logits / denom
    return probs


def _relu(x):
    return np.maximum(x, 0.0)


def _relu_deriv(x):
    return (x > 0.0).astype(np.float64)


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -500.0, 500.0)))


class PolicyValueNet:
    """Shared-trunk MLP with policy and value heads."""

    def __init__(self, board_size=7, hidden_size=192, seed=None):
        self.board_size = board_size
        self.hidden_size = hidden_size
        self.n_cells = _num_cells(board_size)
        input_size = self.n_cells * N_CELL_FEATURES + 2
        rng = np.random.default_rng(seed)

        self.W1 = rng.normal(0.0, math.sqrt(2.0 / input_size), (hidden_size, input_size))
        self.b1 = np.zeros(hidden_size)
        self.Wp = rng.normal(0.0, math.sqrt(2.0 / hidden_size), (self.n_cells, hidden_size))
        self.bp = np.zeros(self.n_cells)
        self.Wv = rng.normal(0.0, math.sqrt(2.0 / hidden_size), (1, hidden_size))
        self.bv = np.zeros(1)

    def forward(self, x):
        z1 = self.W1 @ x + self.b1
        h = _relu(z1)
        logits = self.Wp @ h + self.bp
        value_logit = self.Wv @ h + self.bv
        value = float(_sigmoid(value_logit[0]))
        return logits, value, (x, z1, h, value)

    def predict(self, game, temperature=1.0):
        x = _board_features(game)
        logits, value, _ = self.forward(x)
        legal = [_cell_index(r, c) for r, c in game.legal_moves()]
        policy = _softmax_masked(logits, legal, temperature=temperature)
        return policy, value

    def train_batch(self, xs, policy_targets, value_targets, lr=0.01, value_weight=1.0, l2=1e-5):
        batch_size = xs.shape[0]
        dW1 = np.zeros_like(self.W1)
        db1 = np.zeros_like(self.b1)
        dWp = np.zeros_like(self.Wp)
        dbp = np.zeros_like(self.bp)
        dWv = np.zeros_like(self.Wv)
        dbv = np.zeros_like(self.bv)
        total_loss = 0.0

        for x, policy_target, value_target in zip(xs, policy_targets, value_targets):
            logits, value, cache = self.forward(x)
            _, z1, h, _ = cache

            legal_mask = policy_target > 0.0
            if not np.any(legal_mask):
                continue
            masked_logits = logits[legal_mask]
            masked_logits = masked_logits - np.max(masked_logits)
            exp_logits = np.exp(np.clip(masked_logits, -60.0, 60.0))
            probs_legal = exp_logits / np.sum(exp_logits)
            probs = np.zeros_like(logits)
            probs[legal_mask] = probs_legal

            value_error = value - value_target
            total_loss += -float(np.sum(policy_target[legal_mask] * np.log(probs_legal + 1e-12)))
            total_loss += 0.5 * value_weight * float(value_error * value_error)

            dlogits = probs - policy_target
            dvalue_logit = value_weight * value_error * value * (1.0 - value)

            dWp += np.outer(dlogits, h)
            dbp += dlogits
            dWv += dvalue_logit * h.reshape(1, -1)
            dbv += np.array([dvalue_logit])

            dh = self.Wp.T @ dlogits + dvalue_logit * self.Wv[0]
            dz1 = dh * _relu_deriv(z1)
            dW1 += np.outer(dz1, x)
            db1 += dz1

        inv_batch = 1.0 / max(1, batch_size)
        self.W1 -= lr * (dW1 * inv_batch + l2 * self.W1)
        self.b1 -= lr * db1 * inv_batch
        self.Wp -= lr * (dWp * inv_batch + l2 * self.Wp)
        self.bp -= lr * dbp * inv_batch
        self.Wv -= lr * (dWv * inv_batch + l2 * self.Wv)
        self.bv -= lr * dbv * inv_batch
        return total_loss * inv_batch

    def save(self, path):
        data = {
            "board_size": self.board_size,
            "hidden_size": self.hidden_size,
            "W1": self.W1,
            "b1": self.b1,
            "Wp": self.Wp,
            "bp": self.bp,
            "Wv": self.Wv,
            "bv": self.bv,
        }
        with open(path, "wb") as f:
            pickle.dump(data, f)

    @classmethod
    def load(cls, path):
        with open(path, "rb") as f:
            data = pickle.load(f)
        net = cls(board_size=data["board_size"], hidden_size=data["hidden_size"])
        net.W1 = data["W1"]
        net.b1 = data["b1"]
        net.Wp = data["Wp"]
        net.bp = data["bp"]
        net.Wv = data["Wv"]
        net.bv = data["bv"]
        return net


@dataclass
class TrainingExample:
    features: np.ndarray
    policy: np.ndarray
    player: int
    winner: int = 0
    value: float = 0.5


class PVNode:
    def __init__(self, game, parent=None, move=None, prior=0.0):
        self.game = game
        self.parent = parent
        self.move = move
        self.prior = float(prior)
        self.children = []
        self.visits = 0
        self.value_sum = 0.0

    def q_value(self):
        if self.visits == 0:
            return 0.5
        return self.value_sum / self.visits

    def select_child(self, cpuct):
        best = None
        best_score = -float("inf")
        parent_visits = max(1, self.visits)
        exploration_base = math.sqrt(parent_visits)
        for child in self.children:
            score = child.q_value() + cpuct * child.prior * exploration_base / (1 + child.visits)
            if score > best_score:
                best_score = score
                best = child
        return best

    def expand(self, policy):
        if self.children or self.game.is_over():
            return
        moves = self.game.legal_moves()
        if not moves:
            return
        uniform = 1.0 / len(moves)
        for move in moves:
            idx = _cell_index(move[0], move[1])
            prior = float(policy[idx])
            if prior <= 0.0:
                prior = 0.05 * uniform
            child_game = self.game.copy()
            child_game.make_move(move[0], move[1])
            self.children.append(PVNode(child_game, parent=self, move=move, prior=prior))


def _backpropagate(node, value_player, value):
    while node is not None:
        node.visits += 1
        if node.move is not None:
            if node.game.is_over():
                mover = node.game.winner
            else:
                mover = 3 - node.game.current_player
            node.value_sum += value if mover == value_player else 1.0 - value
        node = node.parent


class PVMCTSAgent:
    """MCTS with trained policy priors and value-network leaf evaluation."""

    def __init__(self, model_path=None, net=None, iterations=1000, cpuct=1.5,
                 policy_temperature=0.85, rollouts_per_leaf=1, value_weight=0.25,
                 rollout_policy="policy"):
        if net is None:
            if model_path is None:
                raise ValueError("PVMCTSAgent needs a model_path or a PolicyValueNet")
            net = PolicyValueNet.load(model_path)
        self.net = net
        self.iterations = iterations
        self.cpuct = cpuct
        self.policy_temperature = policy_temperature
        self.rollouts_per_leaf = rollouts_per_leaf
        self.value_weight = value_weight
        self.rollout_policy = rollout_policy

    def choose_move(self, game):
        moves = game.legal_moves()
        if not moves:
            return None

        me = game.current_player
        for move in moves:
            child = game.copy()
            child.make_move(move[0], move[1])
            if child.winner == me:
                return move

        root = PVNode(game.copy())
        policy, value = self.net.predict(root.game, temperature=self.policy_temperature)
        root.expand(policy)
        _backpropagate(root, root.game.current_player, value)

        for _ in range(self.iterations):
            node = root
            while node.children and not node.game.is_over():
                node = node.select_child(self.cpuct)

            if node.game.is_over():
                value_player = node.game.winner
                leaf_value = 1.0
            else:
                policy, leaf_value = self.net.predict(node.game, temperature=self.policy_temperature)
                value_player = node.game.current_player
                node.expand(policy)
                if self.rollouts_per_leaf > 0:
                    rollout_value = self._rollout_average(node.game, value_player)
                    leaf_value = (
                        self.value_weight * leaf_value
                        + (1.0 - self.value_weight) * rollout_value
                    )

            _backpropagate(node, value_player, leaf_value)

        if not root.children:
            return random.choice(moves)
        best = max(root.children, key=lambda ch: (ch.visits, ch.q_value()))
        return best.move

    def _rollout_average(self, game, value_player):
        total = 0.0
        for _ in range(self.rollouts_per_leaf):
            winner = self._rollout_winner(game)
            total += 1.0 if winner == value_player else 0.0
        return total / self.rollouts_per_leaf

    def _rollout_winner(self, game):
        g = game.copy()
        while not g.is_over():
            moves = g.legal_moves()
            if not moves:
                break

            me = g.current_player
            winning_move = None
            for move in moves:
                child = g.copy()
                child.make_move(move[0], move[1])
                if child.winner == me:
                    winning_move = move
                    break
            if winning_move is not None:
                g.make_move(winning_move[0], winning_move[1])
                continue

            if self.rollout_policy == "policy":
                policy, _ = self.net.predict(g, temperature=1.1)
                weights = np.array([policy[_cell_index(r, c)] for r, c in moves], dtype=np.float64)
                total = float(np.sum(weights))
                if total > 0.0 and np.isfinite(total):
                    idx = int(np.random.choice(len(moves), p=weights / total))
                    move = moves[idx]
                else:
                    move = random.choice(moves)
            else:
                move = random.choice(moves)
            g.make_move(move[0], move[1])
        return g.winner


def _teacher_policy_for_state(game, teacher, rollouts_per_legal=0):
    """Return smoothed policy and value targets from the teacher search."""
    moves = game.legal_moves()
    n_cells = _num_cells(game.board.size)
    policy = np.zeros(n_cells, dtype=np.float64)
    if not moves:
        return policy, None, 0.5

    if rollouts_per_legal <= 0 and hasattr(teacher, "analyze"):
        stats = teacher.analyze(game)
        if stats:
            total_visits = sum(max(0, visits) for _, visits, _ in stats)
            total_wins = sum(max(0.0, wins) for _, _, wins in stats)
            smooth = 0.02
            if total_visits > 0:
                for move, visits, _ in stats:
                    policy[_cell_index(move[0], move[1])] = (
                        (1.0 - smooth) * visits / total_visits + smooth / len(moves)
                    )
                value = total_wins / total_visits
            else:
                for move in moves:
                    policy[_cell_index(move[0], move[1])] = 1.0 / len(moves)
                value = 0.5
            best_move, _, _ = max(stats, key=lambda item: (item[1], item[2]))
            return policy, best_move, float(np.clip(value, 0.0, 1.0))

    if rollouts_per_legal <= 0:
        move = teacher.choose_move(game)
        if move is None:
            move = random.choice(moves)
        # Keep every legal move in the training mask while making the teacher's
        # choice the clear target. Without this smoothing, a one-hot mask makes
        # the policy softmax degenerate to a single logit and no policy gradient.
        smooth = 0.02
        for legal_move in moves:
            policy[_cell_index(legal_move[0], legal_move[1])] = smooth / len(moves)
        policy[_cell_index(move[0], move[1])] += 1.0 - smooth
        return policy, move, 0.5

    from mcts import MCTSAgent

    scores = []
    me = game.current_player
    for move in moves:
        child = game.copy()
        child.make_move(move[0], move[1])
        if child.winner == me:
            scores.append(float(rollouts_per_legal))
            continue
        wins = 0
        for _ in range(rollouts_per_legal):
            reply = MCTSAgent(iterations=max(1, teacher.iterations // 4))
            g = child.copy()
            while not g.is_over():
                m = reply.choose_move(g)
                if m is None:
                    break
                g.make_move(m[0], m[1])
            if g.winner == me:
                wins += 1
        scores.append(float(wins) + 1e-3)

    total = sum(scores)
    if total <= 0.0:
        for move in moves:
            policy[_cell_index(move[0], move[1])] = 1.0 / len(moves)
    else:
        smooth = 0.02
        for move, score in zip(moves, scores):
            policy[_cell_index(move[0], move[1])] = (
                (1.0 - smooth) * score / total + smooth / len(moves)
            )
    best_move = moves[int(np.argmax(scores))]
    return policy, best_move, float(np.clip(max(scores) / max(1.0, rollouts_per_legal), 0.0, 1.0))


def generate_teacher_examples(board_size=7, num_games=200, teacher_iters=2000,
                              rollouts_per_legal=0, out=None):
    """Generate supervised policy/value examples from a plain-MCTS teacher."""
    from game import Game
    from mcts import MCTSAgent

    examples = []
    teacher = MCTSAgent(iterations=teacher_iters)
    for game_idx in range(num_games):
        game = Game(size=board_size)
        game_examples = []
        while not game.is_over():
            policy, move, value = _teacher_policy_for_state(game, teacher, rollouts_per_legal)
            if move is None:
                break
            game_examples.append(
                TrainingExample(
                    features=_board_features(game),
                    policy=policy,
                    player=game.current_player,
                    value=value,
                )
            )
            game.make_move(move[0], move[1])

        for ex in game_examples:
            ex.winner = game.winner
        examples.extend(game_examples)

        if out is not None and (game_idx + 1) % 10 == 0:
            print(f"  PV-MCTS teacher game {game_idx + 1}/{num_games}", file=out, flush=True)

    return examples


def train_policy_value_net(board_size=7, num_games=200, teacher_iters=2000,
                           hidden_size=192, epochs=80, batch_size=64, lr=0.015,
                           rollouts_per_legal=0, seed=7, out=None):
    """Train and return a policy/value network."""
    rng = np.random.default_rng(seed)
    random.seed(seed)
    examples = generate_teacher_examples(
        board_size=board_size,
        num_games=num_games,
        teacher_iters=teacher_iters,
        rollouts_per_legal=rollouts_per_legal,
        out=out,
    )
    if not examples:
        raise RuntimeError("No PV-MCTS training examples were generated")

    xs = np.stack([ex.features for ex in examples])
    policies = np.stack([ex.policy for ex in examples])
    values = np.array([ex.value for ex in examples], dtype=np.float64)

    net = PolicyValueNet(board_size=board_size, hidden_size=hidden_size, seed=seed)
    indices = np.arange(len(examples))
    for epoch in range(epochs):
        rng.shuffle(indices)
        losses = []
        for start in range(0, len(indices), batch_size):
            batch = indices[start:start + batch_size]
            loss = net.train_batch(xs[batch], policies[batch], values[batch], lr=lr)
            losses.append(loss)
        if out is not None and ((epoch + 1) % 10 == 0 or epoch == 0):
            print(
                f"  PV-MCTS epoch {epoch + 1}/{epochs}, loss={np.mean(losses):.4f}",
                file=out,
                flush=True,
            )

    return net


def default_model_path(board_size):
    return os.path.join(os.path.dirname(__file__), "models", f"pv_mcts_model_s{board_size}.pkl")


def load_or_train_pv_mcts(board_size=7, model_path=None, retrain=False,
                          train_games=200, teacher_iters=2000, hidden_size=192,
                          epochs=80, out=None):
    model_path = model_path or default_model_path(board_size)
    if not retrain and os.path.exists(model_path):
        if out is not None:
            print(f"Loaded PV-MCTS policy/value net from {model_path}", file=out)
        return PolicyValueNet.load(model_path), model_path

    if out is not None:
        print(
            f"Training PV-MCTS policy/value net: {train_games} teacher games, "
            f"teacher MCTS={teacher_iters}, board size={board_size}",
            file=out,
            flush=True,
        )
    net = train_policy_value_net(
        board_size=board_size,
        num_games=train_games,
        teacher_iters=teacher_iters,
        hidden_size=hidden_size,
        epochs=epochs,
        out=out,
    )
    os.makedirs(os.path.dirname(model_path), exist_ok=True)
    net.save(model_path)
    if out is not None:
        print(f"Saved PV-MCTS policy/value net to {model_path}", file=out)
    return net, model_path
